# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DSL_calculate_gradient <- function(alpha, Xdata, Kmatrix, sigma2) {
    .Call(`_GSLM_DSL_calculate_gradient`, alpha, Xdata, Kmatrix, sigma2)
}

Calculate_Gradient_order2_Cpp <- function(alpha, Xdata, Kmatrix, sigma2, Ind1, Ind2) {
    .Call(`_GSLM_Calculate_Gradient_order2_Cpp`, alpha, Xdata, Kmatrix, sigma2, Ind1, Ind2)
}

